# SPDX-License-Identifier: Apache-2.0
"""Generate TypeScript types and JSON Schemas from Praelector domain models."""

from __future__ import annotations

import sys
from pathlib import Path

# Ensure engine/src is in python path
sys.path.insert(0, str(Path("engine/src").resolve()))

from praelector.api.v1.health import HealthResponse  # noqa: E402
from praelector.api.v1.version import VersionResponse  # noqa: E402
from praelector.domain.models import (  # noqa: E402
    AppSettings,
    AudioSettings,
    BlockResponse,
    CapabilitiesResponse,
    ChapterMergeRequest,
    ChapterReorderRequest,
    ChapterResponse,
    ChapterSplitRequest,
    ChapterTextResponse,
    ChapterTextUpdate,
    ChapterTextUpdateResponse,
    ChapterUpdate,
    DrmStatus,
    GpuPolicy,
    IngestConvertOptions,
    IngestProbeRequest,
    IngestProbeResponse,
    IngestRequest,
    IngestResponse,
    KeyringProbe,
    LlmProfile,
    LlmProfileWrite,
    MetadataPreview,
    ProjectCounts,
    ProjectCreate,
    ProjectOpenResponse,
    ProjectResponse,
    ProjectSourceResponse,
    ProjectStats,
    ProjectSummary,
    ProjectUpdate,
    ReplacePreview,
    ReplaceRequest,
    ReplaceResponse,
    RuntimeProbe,
    SearchHit,
    SearchRequest,
    SearchResponse,
    SecretField,
    SettingsUpdate,
    SpanCreate,
    SpanResponse,
    SpanUpdate,
    TaskRouting,
    ToolProbe,
)


def _ts_type(prop: dict[str, object]) -> str:
    """Map JSON Schema property to TypeScript type."""
    if "$ref" in prop:
        return str(prop["$ref"]).split("/")[-1]

    any_of = prop.get("anyOf")
    if isinstance(any_of, list):
        types = [_ts_type(sub) for sub in any_of if isinstance(sub, dict)]
        return " | ".join(types)

    prop_type = prop.get("type")
    if prop_type == "string":
        enum_vals = prop.get("enum")
        if isinstance(enum_vals, list):
            return " | ".join(f'"{val}"' for val in enum_vals)
        return "string"
    if prop_type in ("integer", "number"):
        return "number"
    if prop_type == "boolean":
        return "boolean"
    if prop_type == "array":
        items = prop.get("items")
        if isinstance(items, dict):
            return f"{_ts_type(items)}[]"
        return "unknown[]"
    if prop_type == "object":
        add_props = prop.get("additionalProperties")
        if isinstance(add_props, dict):
            val_type = _ts_type(add_props)
            return f"Record<string, {val_type}>"
        return "Record<string, unknown>"
    if prop_type == "null":
        return "null"

    return "unknown"


def generate_ts() -> str:
    """Generate complete TypeScript file content from Pydantic schemas."""
    models = [
        HealthResponse,
        VersionResponse,
        ProjectCounts,
        ProjectResponse,
        ProjectSummary,
        ProjectCreate,
        ProjectUpdate,
        ProjectOpenResponse,
        ProjectStats,
        SecretField,
        LlmProfile,
        LlmProfileWrite,
        TaskRouting,
        GpuPolicy,
        AudioSettings,
        AppSettings,
        SettingsUpdate,
        ToolProbe,
        KeyringProbe,
        RuntimeProbe,
        CapabilitiesResponse,
        DrmStatus,
        MetadataPreview,
        IngestProbeRequest,
        IngestProbeResponse,
        IngestConvertOptions,
        IngestRequest,
        IngestResponse,
        ProjectSourceResponse,
        ChapterResponse,
        ChapterUpdate,
        ChapterReorderRequest,
        ChapterSplitRequest,
        ChapterMergeRequest,
        BlockResponse,
        ChapterTextResponse,
        ChapterTextUpdate,
        ChapterTextUpdateResponse,
        SpanResponse,
        SpanCreate,
        SpanUpdate,
        SearchRequest,
        SearchHit,
        SearchResponse,
        ReplaceRequest,
        ReplacePreview,
        ReplaceResponse,
    ]

    output: list[str] = [
        "// SPDX-License-Identifier: Apache-2.0",
        "/**",
        " * Generated TypeScript contracts from Praelector domain models.",
        " * AUTO-GENERATED BY scripts/gen_ts_types.py. DO NOT EDIT DIRECTLY.",
        " */",
        "",
        'export type VoiceMode = "single" | "narrator_dialogue" | "narrator_male_female";',
        'export type VoiceSlot = "narrator" | "dialogue" | "male" | "female";',
        'export type SourceFormat = "epub" | "pdf" | "mobi" | "azw3";',
        'export type BlockKind = "paragraph" | "heading" | "blockquote" | "list_item" | "caption";',
        'export type SpanKind = "narration" | "dialogue" | "pronunciation" | "pause" | "skip";',
        'export type SpanOrigin = "auto_frontmatter" | "auto_dialogue" | "auto_pronounce" | "manual";',
        'export type Gender = "male" | "female" | "unknown";',
        'export type GenderDetector = "regex_pl" | "heuristic" | "cloud_llm" | "manual";',
        'export type DrmReason = "font_obfuscation" | "encrypted_content" | "rights_xml" | "sinf_xml" | "unknown";',
        "export type SuggestionCategory =",
        '  | "foreign_word"',
        '  | "acronym"',
        '  | "toponym"',
        '  | "numeral"',
        '  | "ordinal_heading"',
        '  | "dialogue_split"',
        '  | "speaker_gender"',
        '  | "conversion_artifact"',
        '  | "dict_hit";',
        'export type SuggestionStatus = "pending" | "accepted" | "rejected" | "edited" | "failed";',
        'export type JobKind = "prep" | "record";',
        'export type JobState = "queued" | "running" | "paused" | "muxing" | "done" | "failed" | "cancelled";',
        'export type JobStage = "plan" | "synth" | "mux";',
        "",
        "export interface ErrorPayload {",
        "  code: string;",
        "  detail: Record<string, unknown>;",
        "  retryable: boolean;",
        "  trace_id: string;",
        "}",
        "",
        "export interface ErrorEnvelope {",
        "  error: ErrorPayload;",
        "}",
        "",
    ]

    for model in models:
        schema = model.model_json_schema()
        name = schema.get("title", model.__name__)
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))

        output.append(f"export interface {name} {{")
        for prop_name, prop_data in properties.items():
            if not isinstance(prop_data, dict):
                continue
            opt = "" if prop_name in required else "?"
            ts_t = _ts_type(prop_data)
            output.append(f"  {prop_name}{opt}: {ts_t};")
        output.append("}")
        output.append("")

    return "\n".join(output)


def main() -> int:
    schemas_dir = Path("packages/schemas/src/json")
    types_dir = Path("packages/schemas/src/generated")

    schemas_dir.mkdir(parents=True, exist_ok=True)
    types_dir.mkdir(parents=True, exist_ok=True)

    ts_content = generate_ts()
    target_ts = types_dir / "index.ts"
    target_ts.write_text(ts_content, encoding="utf-8")

    print(f"Generated TypeScript interfaces at {target_ts}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
