#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the UI/engine contract: Pydantic models -> JSON Schema -> TypeScript."""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
import tempfile
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
ENGINE_SRC = Path("engine") / "src"
SCHEMAS_SRC = Path("packages") / "schemas" / "src"
JSON_DIR = SCHEMAS_SRC / "json"
GENERATED_DIR = SCHEMAS_SRC / "generated"

STEM_RE = re.compile(r"^[a-z][a-z0-9_]*$")
JS_IDENT_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")
REF_PREFIX = "#/$defs/"


@dataclass(frozen=True)
class Export:
    """One exported type: where to import it from and what to call the JSON Schema."""

    module: str
    attr: str
    stem: str


# The contract registry. It grows with the codebase: add the line for a new model in
# the PR that introduces the model, not before. An entry that cannot be imported or
# that is not a Pydantic/enum type fails the run (exit 1) rather than being skipped,
# so the UI can never silently lose a type it depends on.
EXPORTS: tuple[Export, ...] = (
    # WebSocket wire envelope (OPENAPI_SKETCH.md §11).
    Export("praelector.domain.models", "WsEnvelope", "ws_envelope"),
    # Enumerations. Each is a StrEnum, so each becomes a string literal union in TS.
    Export("praelector.domain.enums", "BlockKind", "block_kind"),
    Export("praelector.domain.enums", "Detector", "detector"),
    Export("praelector.domain.enums", "EventType", "event_type"),
    Export("praelector.domain.enums", "EpubVariant", "epub_variant"),
    Export("praelector.domain.enums", "Gender", "gender"),
    Export("praelector.domain.enums", "GpuVendor", "gpu_vendor"),
    Export("praelector.domain.enums", "JobKind", "job_kind"),
    Export("praelector.domain.enums", "JobStage", "job_stage"),
    Export("praelector.domain.enums", "JobState", "job_state"),
    Export("praelector.domain.enums", "LlmPreset", "llm_preset"),
    Export("praelector.domain.enums", "LlmProviderKind", "llm_provider_kind"),
    Export("praelector.domain.enums", "MuxMode", "mux_mode"),
    Export("praelector.domain.enums", "PauseMode", "pause_mode"),
    Export("praelector.domain.enums", "Precision", "precision"),
    Export("praelector.domain.enums", "RuntimeFlavour", "runtime_flavour"),
    Export("praelector.domain.enums", "SourceFormat", "source_format"),
    Export("praelector.domain.enums", "SpanKind", "span_kind"),
    Export("praelector.domain.enums", "SpanOrigin", "span_origin"),
    Export("praelector.domain.enums", "SuggestionCategory", "suggestion_category"),
    Export("praelector.domain.enums", "SuggestionStatus", "suggestion_status"),
    Export("praelector.domain.enums", "TaskKey", "task_key"),
    Export("praelector.domain.enums", "VoiceMode", "voice_mode"),
    Export("praelector.domain.enums", "VoiceSlot", "voice_slot"),
    Export("praelector.domain.ids", "IdPrefix", "id_prefix"),
    # Error contract (D-16): the UI renders codes, never engine prose.
    Export("praelector.errors", "ErrorCode", "error_code"),
    Export("praelector.errors", "ErrorBody", "error_body"),
    Export("praelector.errors", "ErrorResponse", "error_response"),
    # HTTP responses. Schemas are generated by_alias so they match what FastAPI puts
    # on the wire (e.g. VersionResponse.schema_version is serialised as "schema").
    Export("praelector.api.v1.health", "HealthResponse", "health_response"),
    Export("praelector.api.v1.health", "VersionResponse", "version_response"),
    Export("praelector.api.v1.health", "PlatformInfo", "platform_info"),
    Export("praelector.api.v1.health", "ShutdownResponse", "shutdown_response"),
    Export("praelector.api.v1.ws", "ClientOp", "client_op"),
)


class GenerationError(RuntimeError):
    """A model could not be resolved or rendered; reported as exit code 1."""


def skip_message() -> None:
    print(
        f"SKIP  {ENGINE_SRC.as_posix()}/praelector does not exist yet.\n"
        "\n"
        "      The engine package lands in a later PR of this stacked series, so\n"
        "      nothing was generated. NO CHECK RAN — this is not a pass, it is a\n"
        "      skip; the staleness gate in ci-ui.yml switches on automatically once\n"
        "      engine/src/praelector exists."
    )


def to_snake_case(name: str) -> str:
    split = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", split).lower()


def load_models(root: Path) -> list[tuple[Export, Any]]:
    src = (root / ENGINE_SRC).resolve()
    if str(src) not in sys.path:
        sys.path.insert(0, str(src))

    try:
        from pydantic import TypeAdapter
    except ImportError as exc:
        raise GenerationError(
            f"pydantic is not importable ({exc}). Run this through the engine "
            f"environment: `uv run --project engine python scripts/gen_ts_types.py`"
        ) from exc

    import importlib

    loaded: list[tuple[Export, Any]] = []
    for export in EXPORTS:
        if not STEM_RE.match(export.stem):
            raise GenerationError(f"EXPORTS stem {export.stem!r} is not snake_case")
        if to_snake_case(export.attr) != export.stem:
            raise GenerationError(
                f"EXPORTS stem {export.stem!r} does not match {export.attr!r} "
                f"(expected {to_snake_case(export.attr)!r})"
            )
        try:
            module = importlib.import_module(export.module)
        except ImportError as exc:
            raise GenerationError(
                f"cannot import {export.module} (needed for {export.stem}.json): {exc}\n"
                f"       either that engine module has not landed yet, or the EXPORTS "
                f"entry in scripts/gen_ts_types.py names the wrong path"
            ) from exc
        model = getattr(module, export.attr, None)
        if model is None:
            raise GenerationError(
                f"{export.module} has no attribute {export.attr!r} "
                f"(needed for {export.stem}.json); fix the EXPORTS entry"
            )
        try:
            # TypeAdapter rather than model.model_json_schema(): most exports are
            # StrEnum members, which have no model_json_schema of their own.
            TypeAdapter(model)
        except Exception as exc:
            raise GenerationError(
                f"{export.module}.{export.attr} is not a Pydantic model, enum or "
                f"type TypeAdapter can handle: {exc}"
            ) from exc
        loaded.append((export, model))
    return loaded


def restore_formats(validated: Any, serialised: Any) -> Any:
    """Copy `format` annotations that serialisation mode erases.

    A `field_serializer` returning `str` makes the serialisation schema say only
    `{"type": "string"}`, losing `format: date-time` — but the bytes on the wire are
    still RFC 3339, so the annotation is carried over from the validation schema.
    Names and shapes stay whatever serialisation mode produced.
    """
    if isinstance(serialised, dict):
        out = dict(serialised)
        if (
            "format" not in out
            and out.get("type") == "string"
            and isinstance(validated, dict)
            and validated.get("type") == "string"
            and isinstance(validated.get("format"), str)
        ):
            out["format"] = validated["format"]
        if isinstance(validated, dict):
            for key, value in out.items():
                if isinstance(value, (dict, list)) and key in validated:
                    out[key] = restore_formats(validated[key], value)
        return out
    if isinstance(serialised, list) and isinstance(validated, list):
        if len(validated) == len(serialised):
            return [
                restore_formats(item, entry)
                for item, entry in zip(validated, serialised, strict=True)
            ]
        return serialised
    return serialised


def build_schemas(models: Sequence[tuple[Export, Any]]) -> dict[str, dict[str, Any]]:
    from pydantic import TypeAdapter

    schemas: dict[str, dict[str, Any]] = {}
    for export, model in models:
        adapter = TypeAdapter(model)
        try:
            # Serialisation mode + by_alias: FastAPI serialises responses by alias, so
            # a validation-mode schema would describe a payload the engine never sends
            # (VersionResponse.schema_version goes out as "schema").
            # Self-contained per model: every $ref stays inside $defs so each JSON file
            # can be consumed and diffed on its own.
            serialised = adapter.json_schema(
                by_alias=True, mode="serialization", ref_template=f"{REF_PREFIX}{{model}}"
            )
            validated = adapter.json_schema(
                by_alias=True, mode="validation", ref_template=f"{REF_PREFIX}{{model}}"
            )
        except Exception as exc:  # pydantic raises several unrelated types here
            raise GenerationError(
                f"JSON Schema generation failed for {export.module}.{export.attr}: {exc}"
            ) from exc
        schema = restore_formats(validated, serialised)
        if not isinstance(schema, dict):
            raise GenerationError(f"{export.stem}: schema is not an object")
        schemas[export.stem] = schema
    return schemas


def write_json(
    out_dir: Path, exports: Sequence[Export], schemas: Mapping[str, dict[str, Any]]
) -> None:
    target = out_dir / JSON_DIR
    target.mkdir(parents=True, exist_ok=True)
    for export in exports:
        body = json.dumps(schemas[export.stem], indent=2, ensure_ascii=False, sort_keys=True)
        (target / f"{export.stem}.json").write_text(body + "\n", encoding="utf-8", newline="\n")

    index = {
        "description": "Praelector UI/engine contract, generated from the engine's Pydantic models.",
        "generated_by": "scripts/gen_ts_types.py",
        "schemas": [
            {
                "name": export.stem,
                "file": f"{export.stem}.json",
                "model": f"{export.module}.{export.attr}",
                "type": export.attr,
            }
            for export in sorted(exports, key=lambda e: e.stem)
        ],
    }
    (target / "index.json").write_text(
        json.dumps(index, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n"
    )


def quote_property(name: str) -> str:
    return name if JS_IDENT_RE.match(name) else json.dumps(name)


def ts_type_name(name: str) -> str:
    sanitised = re.sub(r"[^A-Za-z0-9_$]", "_", name)
    if not JS_IDENT_RE.match(sanitised):
        sanitised = f"T_{sanitised}"
    return sanitised


def render_type(schema: Any, defs: Mapping[str, Any]) -> str:
    """Render one JSON Schema node as a TypeScript type expression."""
    if schema is True or schema is None:
        return "unknown"
    if schema is False:
        return "never"
    if not isinstance(schema, dict):
        return "unknown"

    if "$ref" in schema:
        ref = str(schema["$ref"])
        return ts_type_name(ref[len(REF_PREFIX) :]) if ref.startswith(REF_PREFIX) else "unknown"

    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)

    branches: list[str] = []
    for key in ("anyOf", "oneOf"):
        for branch in schema.get(key) or []:
            branches.append(render_type(branch, defs))
    for branch in schema.get("allOf") or []:
        rendered = render_type(branch, defs)
        branches.append(f"({rendered})" if " | " in rendered else rendered)
    if branches:
        # A node that also carries its own type/enum describes an intersection of
        # constraints; render both sides so nothing is silently dropped.
        if "enum" in schema or "type" in schema or "properties" in schema:
            branches.append(render_scalar(schema, defs))
        return " | ".join(dict.fromkeys(branches))

    return render_scalar(schema, defs)


def render_scalar(schema: Mapping[str, Any], defs: Mapping[str, Any]) -> str:
    if "enum" in schema:
        values = schema["enum"]
        if isinstance(values, list) and values:
            return " | ".join(json.dumps(value, ensure_ascii=False) for value in values)
        return "unknown"

    declared = schema.get("type")
    types = declared if isinstance(declared, list) else [declared] if declared else []
    rendered: list[str] = []
    for item in types:
        if item == "object":
            rendered.append(render_object(schema, defs))
        elif item == "array":
            rendered.append(render_array(schema, defs))
        elif item in {"integer", "number"}:
            rendered.append("number")
        elif item == "string":
            rendered.append("string")
        elif item == "boolean":
            rendered.append("boolean")
        elif item == "null":
            rendered.append("null")
        else:
            rendered.append("unknown")

    if not rendered:
        if "properties" in schema or "additionalProperties" in schema:
            rendered.append(render_object(schema, defs))
        elif "items" in schema or "prefixItems" in schema:
            rendered.append(render_array(schema, defs))
        else:
            rendered.append("unknown")

    return " | ".join(dict.fromkeys(rendered))


def render_array(schema: Mapping[str, Any], defs: Mapping[str, Any]) -> str:
    prefix = schema.get("prefixItems")
    if isinstance(prefix, list) and prefix:
        return "[" + ", ".join(render_type(item, defs) for item in prefix) + "]"
    items = schema.get("items")
    if isinstance(items, list):
        return "[" + ", ".join(render_type(item, defs) for item in items) + "]"
    element = render_type(items, defs) if items is not None else "unknown"
    # A union element needs parentheses or `A | B[]` would bind to B only.
    return f"Array<{element}>" if " | " in element or " & " in element else f"{element}[]"


def render_object(schema: Mapping[str, Any], defs: Mapping[str, Any]) -> str:
    properties = schema.get("properties")
    additional = schema.get("additionalProperties")
    if not isinstance(properties, Mapping) or not properties:
        if isinstance(additional, Mapping):
            return f"Record<string, {render_type(additional, defs)}>"
        return "Record<string, unknown>"

    required = set(schema.get("required") or [])
    parts: list[str] = []
    # Property order comes from the Pydantic model, which is stable; sorting it would
    # hide the reading order the engine authors chose.
    for name, value in properties.items():
        optional = "" if name in required else "?"
        parts.append(f"{quote_property(str(name))}{optional}: {render_type(value, defs)}")
    if additional is True:
        parts.append("[key: string]: unknown")
    elif isinstance(additional, Mapping):
        parts.append(f"[key: string]: {render_type(additional, defs)}")
    return "{ " + "; ".join(parts) + " }"


def doc_comment(schema: Mapping[str, Any], indent: str) -> str:
    description = schema.get("description")
    if not isinstance(description, str) or not description.strip():
        return ""
    lines = [line.strip() for line in description.strip().splitlines()]
    body = "\n".join(f"{indent} * {line}".rstrip() for line in lines)
    return f"{indent}/**\n{body}\n{indent} */"


def declaration(name: str, schema: Mapping[str, Any], defs: Mapping[str, Any]) -> tuple[str, str]:
    """Return (body, full declaration) for one named type."""
    head = doc_comment(schema, "")
    properties = schema.get("properties")
    additional = schema.get("additionalProperties")

    if isinstance(properties, Mapping) and properties:
        required = set(schema.get("required") or [])
        body = [f"export interface {name} {{"]
        for prop_name, value in properties.items():
            if isinstance(value, Mapping):
                comment = doc_comment(value, "  ")
                if comment:
                    body.append(comment)
            optional = "" if prop_name in required else "?"
            body.append(
                f"  {quote_property(str(prop_name))}{optional}: {render_type(value, defs)};"
            )
        if additional is True:
            body.append("  [key: string]: unknown;")
        elif isinstance(additional, Mapping):
            body.append(f"  [key: string]: {render_type(additional, defs)};")
        body.append("}")
        text = "\n".join(body)
        return text, f"{head}\n{text}" if head else text

    text = f"export type {name} = {render_type(schema, defs)};"
    return text, f"{head}\n{text}" if head else text


def emit_index_ts(exports: Sequence[Export], schemas: Mapping[str, dict[str, Any]]) -> str:
    """One module with every type inline, shared $defs deduplicated.

    Cross-file imports would need a module per $def and still could not express a
    type that two models share; a single deterministic file is what the UI imports
    (`@praelector/schemas` points at generated/index.ts).
    """
    bodies: dict[str, str] = {}
    rendered: dict[str, str] = {}
    provenance: dict[str, str] = {}

    def register(
        name: str, schema: Mapping[str, Any], defs: Mapping[str, Any], origin: str
    ) -> None:
        type_name = ts_type_name(name)
        body, full = declaration(type_name, schema, defs)
        if type_name in bodies:
            if bodies[type_name] != body:
                raise GenerationError(
                    f"{type_name} is generated twice with different shapes "
                    f"({provenance[type_name]} and {origin}); the contract is ambiguous"
                )
            return
        bodies[type_name] = body
        rendered[type_name] = full
        provenance[type_name] = origin

    # Top-level exports win over a same-named $def nested inside another model.
    for export in exports:
        schema = schemas[export.stem]
        defs = schema.get("$defs") if isinstance(schema.get("$defs"), Mapping) else {}
        register(export.attr, schema, defs, f"{export.module}.{export.attr}")
    for export in exports:
        schema = schemas[export.stem]
        defs = schema.get("$defs") if isinstance(schema.get("$defs"), Mapping) else {}
        for def_name in sorted(defs):
            register(def_name, defs[def_name], defs, f"{export.stem}.json#/$defs/{def_name}")

    parts = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Generated by scripts/gen_ts_types.py — do not edit by hand.",
        "// Source: the engine's Pydantic models; regenerate with `just codegen`.",
        "",
    ]
    for type_name in sorted(rendered):
        parts.append(rendered[type_name])
        parts.append("")
    return "\n".join(parts)


def write_generated(
    out_dir: Path, exports: Sequence[Export], schemas: Mapping[str, dict[str, Any]]
) -> None:
    target = out_dir / GENERATED_DIR
    target.mkdir(parents=True, exist_ok=True)
    (target / "index.ts").write_text(
        emit_index_ts(exports, schemas), encoding="utf-8", newline="\n"
    )


def generate(root: Path, out_dir: Path) -> tuple[list[Path], int]:
    models = load_models(root)
    schemas = build_schemas(models)
    exports = [export for export, _ in models]
    write_json(out_dir, exports, schemas)
    write_generated(out_dir, exports, schemas)
    written = sorted(path for path in (out_dir / SCHEMAS_SRC).rglob("*") if path.is_file())
    return written, len(exports)


def compare_trees(expected: Path, actual: Path) -> list[str]:
    problems: list[str] = []
    produced: dict[str, str] = {}
    for path in sorted(expected.rglob("*")):
        if path.is_file():
            produced[path.relative_to(expected).as_posix()] = path.read_text(encoding="utf-8")

    on_disk: dict[str, str] = {}
    if actual.is_dir():
        for path in sorted(actual.rglob("*")):
            # Placeholders keep the empty directories in git; this script never
            # deletes files, so they are not drift.
            if path.is_file() and path.name != ".gitkeep":
                on_disk[path.relative_to(actual).as_posix()] = path.read_text(encoding="utf-8")

    for name in sorted(produced.keys() - on_disk.keys()):
        problems.append(f"would be created: {name}")
    for name in sorted(on_disk.keys() - produced.keys()):
        problems.append(f"would be deleted: {name}")
    for name in sorted(produced.keys() & on_disk.keys()):
        if produced[name] == on_disk[name]:
            continue
        diff = list(
            difflib.unified_diff(
                on_disk[name].splitlines(),
                produced[name].splitlines(),
                fromfile=f"committed/{name}",
                tofile=f"generated/{name}",
                lineterm="",
                n=1,
            )
        )
        problems.append(f"differs: {name}")
        problems.extend(f"    {line}" for line in diff[:24])
        if len(diff) > 24:
            problems.append(f"    … {len(diff) - 24} more diff line(s)")
    return problems


def parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="gen_ts_types.py",
        description=(
            "Export the engine's Pydantic models as JSON Schema plus a single "
            "TypeScript module under packages/schemas, so the UI can never drift "
            "from the engine contract. CI_AND_RELEASE.md §3 names "
            "json-schema-to-typescript; this emits TypeScript itself so the output is "
            "one deterministic file with shared $defs deduplicated, and codegen does "
            "not depend on a Node install."
        ),
        epilog=(
            "exit codes: 0 generated (or nothing to generate yet), 1 an EXPORTS entry "
            "could not be resolved or --check found drift, 2 usage error"
        ),
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=REPO_ROOT,
        help="repository root (default: the parent of scripts/)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="generate into a temporary directory and report drift instead of writing",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="print the EXPORTS registry and exit",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    root: Path = args.root.resolve()
    if not root.is_dir():
        print(f"error: --root is not a directory: {root}", file=sys.stderr)
        return 2

    if args.list:
        for export in EXPORTS:
            print(f"{export.stem:24} {export.module}.{export.attr}")
        return 0

    if not (root / ENGINE_SRC / "praelector").is_dir():
        skip_message()
        return 0

    if args.check:
        with tempfile.TemporaryDirectory(prefix="praelector-schemas-") as tmp:
            staging = Path(tmp)
            try:
                _, count = generate(root, staging)
            except GenerationError as exc:
                print(f"error: {exc}", file=sys.stderr)
                return 1
            problems = compare_trees(staging / SCHEMAS_SRC, root / SCHEMAS_SRC)
        if problems:
            print(f"FAIL: packages/schemas is stale ({count} model(s) exported)", file=sys.stderr)
            for line in problems:
                print(f"  {line}", file=sys.stderr)
            print(
                "  regenerate with `uv run --project engine python scripts/gen_ts_types.py`",
                file=sys.stderr,
            )
            return 1
        print(f"ok: packages/schemas matches the engine models ({count} exported)")
        return 0

    try:
        written, count = generate(root, root)
    except GenerationError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(
        f"wrote {len(written)} artifact(s) for {count} exported type(s) "
        f"under {SCHEMAS_SRC.as_posix()}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
